### PR TITLE
Check for method in multipart form data.

### PR DESCRIPTION
**Pull request by mgritter**
Added unit test for method extraction.
Refactored host test into its own function.

### CODE REVIEW

**Comment by mgritter** [comment]
Some of the examples I pulled from production data seemed to work fine in the unit test harness.  So could be a problem in the CLI where we're not calling the plugin? Or that the plugin was inconsistently enabled.

**Comment by mgritter** [comment]
attn @nscheiblauer , looks like I can't add you as a reviewer

**Review by nscheiblauer — APPROVED** [review]
Thanks, @mgritter !

**Review by liujed — APPROVED** [review]
Looks plausible. Also relaying Nick's approval.

**Review by yaseedee1 — APPROVED** [review]

**Comment by Ppmahadevan** [comment]
Thanking you

**Pull request merged**
